language: rust
rust: nightly
script:
- cargo build --verbose
after_success:
- cargo doc
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
env:
  global:
  - secure: UNMFgfqtYsf249eimjShzdDzb85EALHuEz1awhLGaojnq7szpNeVKab6MrcqyCZBKEyEoh2LAniAog6Y+0WA8A+Po7SoeLrMbTv+Dfrahl1NOaNqqTEm24egVOdX2rFPHYyBh9vu8vGbKuWkjbp3KhES8y80UAukI1DdA1NpgWA8YHWOiRCTjTtXrFOFsOUwbpQ5syiOU6vuZDQfGjg58AeJRXUQyYT8gDBc2mEIFJuvhNpxrIBr4op6+wdjuDPOzPUC9DdbTLLCDKKNxXw0uopu+ezGYr4aq4XJQlHF1vOF7rn8iZVg6kgN2nlpqzxArRMzWvAl4oyGxWyExBJYsZWm6GO1oWyXGGYDc7jXyz5gVd4KONd6Y/Q+yp6jt1Xj3bof4u/APXn4elN4rofth5SjSLrWIufe4uMIY8xM+jfoEtArFtGdMmu3uZwNvy4YeRh7zvqBL2tILR5j/cTTNk0sXk1+z2babuc3EVSig7TDDhMCpxZbzp4CavB7CjOMboBQU3wjVYGB/lVaAU4t4Whz+mWP5VIe9qElNQEv3eqVygdujEffr2OG8NrhGeF3ONyuImJk1k5UDV/UU3ne8zRL9AoaRTkBvRlUeJyuZsAB+1+UF7N9NhtbCM3Qxd/PTe/8OkxntYc997X3+FQxVQWIt/9Q/k4u5c6hQbgwMco=
